### PR TITLE
clean up package json

### PR DESCRIPTION
**Pull request by romadryud**
### Related to
Issue #21 

### Notes

Before after installing packages we [had](https://pastebin.ubuntu.com/p/XnZkNm8VGT/) more than 1000 additions in yarn.lock.

After we [have](https://pastebin.ubuntu.com/p/qwCM4dKgg6/) less than 30 lines. 

Bundle size doesn't change a lot because of good tree-shaking in the rollup. To be honest, I have the same size as before the changes.

Commits are independent, in case you want to cherry-pick some of them. 

I added one commit related to a warning about source maps during the build.

Yarn used to create a lock file because it mention in `package.json`

### Types of changes
-   [ ]   :bug: Bug fix
-   [ ]   :boom: Breaking change
-   [ ]   :sparkles: New feature
-   [x]   :recycle: Refactoring
-   [ ]   :book: Documentation

### Maintainability & Security
-   [ ]   🧪  unit test

### CODE REVIEW

**Comment by romadryud** [comment]
@thomasbrodusch Could you please review this one in free time? Thank you!

PS:
I rebased a branch to have proper commit message so that's why this is a slide in 4 hours for 2 commits :)

**Review by thomasbrodusch — APPROVED** [review]
LGTM 🌱 
Thanks for this work @romadryud 👍

**Comment by romadryud** [comment]
@thomasbrodusch Thank you! When did you plan to release a new version of the package?

**Comment by thomasbrodusch** [comment]
I plan to add a Dependabot feature in addition to your PR to handle dependencies versioning.
When it's done I'll publish a new release.

**Pull request merged**
